version: '3.8'

services:
  postgres:
    image: quay.io/element84/swoop-db:latest
    restart: always
    environment:
      POSTGRES_DB: "${PGDATABASE:-swoop}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-password}"
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: "${PGAUTHMETHOD:-trust}"
    ports:
      - "${PGPORT:-5432}:5432"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${SWOOP_ACCESS_KEY_ID:-minio}"
      MINIO_ROOT_PASSWORD: "${SWOOP_SECRET_ACCESS_KEY:-password}"
      SWOOP_BUCKET_NAME: "${SWOOP_BUCKET_NAME:-swoop}"
    entrypoint: bash -c 'mkdir -p "$${1}/${SWOOP_BUCKET_NAME}" && exec minio server --console-address ":9001" "$${1}"' -- "/tmp/minio"

  api:
    build: .
    restart: always
    profiles:
      - api
    environment:
      MINIO_ACCESS_KEY: "${MINIO_ACCESS_KEY:-minio}"
      MINIO_SECRET_KEY: "${MINIO_SECRET_KEY:-password}"
      SWOOP_S3_ENDPOINT: "http://minio:9000"
      SWOOP_BUCKET_NAME: "${SWOOP_BUCKET_NAME:-swoop}"
      SWOOP_EXECUTION_DIR: "${SWOOP_EXECUTION_DIR:-s3://swoop/execution}"
      PGDATABASE: "${PGDATABASE:-swoop}"
      PGHOST: "postgres"
      PGUSER: "${PGUSER:-postgres}"
      UVICORN_HOST: "${UVICORN_HOST:-0.0.0.0}"
      UVICORN_PORT: "${UVICORN_PORT:-8000}"
    ports:
      - "${UVICORN_PORT:-8000}:${UVICORN_PORT:-8000}"
    depends_on:
      - postgres
      - minio
