version: '3.8'

services:
  postgres:
    build:
      context: ./db
      dockerfile: Dockerfile
    restart: always
    environment:
      POSTGRES_DB: "${PGDATABASE:-postgres}"
      POSTGRES_PASSWORD: "${PGPASSWORD:-password}"
      POSTGRES_USER: "${PGUSER:-postgres}"
      POSTGRES_HOST_AUTH_METHOD: "trust"
    ports:
      - "${DATABASE_PORT:-5432}:5432"
    volumes:
      - "./:/swoop"
    working_dir: "/swoop"

  minio:
    image: quay.io/minio/minio
    ports:
      - "9000:9000"
      - "9001:9001"
    environment:
      MINIO_ROOT_USER: "${AWS_ACCESS_KEY_ID:-minio}"
      MINIO_ROOT_PASSWORD: "${AWS_SECRET_ACCESS_KEY:-password}"
      SWOOP_BUCKET_NAME: "${SWOOP_BUCKET_NAME:-swoop}"
    entrypoint: bash -c 'mkdir -p "$${1}/${SWOOP_BUCKET_NAME}" && exec minio server --console-address ":9001" "$${1}"' -- "/tmp/minio"
