workflows:
  mirror:
    description: "A workflow to copy STAC items into a local mirror"
    version: 2
    handler: argo-handler
    type: argo-workflow
    argoTemplate: workflowtemplate/mirror-workflow
    cacheKeyHashIncludes:
      - .features[].id
      - .features[].collection
    cacheKeyHashExcludes: []
  cirrus-example:
    description: "An example workflow config for a cirrus workflow"
    version: 1
    handler: cirrus-handler
    type: cirrus-workflow
    sfnArn: arn:aws:states:us-west-2:09876543210:stateMachine:cirrus-example
    cacheKeyHashIncludes:
      - .features[].id
      - .features[].collection
    cacheKeyHashExcludes: []
